ch11/blog/urls.py
from django.urls import path, re_path
from blog import views

# 이 파일은 ch03에서 신규 생성된다.
# blog를 위한 App Url파일이다.

app_name = 'blog'

urlpatterns = [
    # 호출 예시) /blog/
    path('', views.PostLV.as_view(), name='index'),

    # 호출 예시) /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 호출 예시) /blog/post/xxx/    정규식
    # r'정규표현식'의 r은 raw string의 줄인 말
    # cf) '\d'는 숫자 1개를 의미하고, r'\d'는 역슬래시 1개와 d를 찾아준다.
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDV.as_view(), name='post_detail'),

    # 호출 예시) /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # 호출 예시) /blog/archive/2021/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 호출 예시) /blog/archive/2021/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 호출 예시) /blog/archive/2021/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # 호출 예시) /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # 호출 예시) /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # 호출 예시) /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # 호출 예시) /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

ch11/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include # ch03에서 추가됨
from mysite.views import HomeView # ch04에서 추가됨

from django.conf.urls.static import static # ch09에서 추가됨
from django.conf import settings    # ch09에서 추가됨

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 관리자를 위한 페이지
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'), # ch04에서 추가됨

    path('bookmark/', include('bookmark.urls')),    # ch03에서 추가됨
    path('blog/', include('blog.urls')),    # ch03에서 추가됨

    path('photo/', include('photo.urls')),  # ch09에서 추가됨

    # acoounts 항목들을 인증 기능(ch10)에서 추가됨
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='=register_done')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  # ch09에서 추가됨
    # Django의 보안상의 문제로 인해 새롭게 업로드 되는 이미지나 css, js파일과 같은 정적
    # 파일들의 경로를 실시간으로 읽어오지 못하기 때문에 뒤로 경로를 따로 설정해 주었다.


    # 기존 소스 주석 처리
    # # 사용자를 위한 페이지 - 사용자가 지정한 views
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    #
    # # <int:pk>는 정수형 primary key를 의미할 것 같다고(-같다! 고 말하심)
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),]

ch11/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns = [
    # 호출 예시: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # 호출 예시: /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    # 호출 예시: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # 호출 예시: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
]

ch11/photo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    name = models.CharField('NAME', max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ('name', )   # ('ex', ) 이렇게 적어야 튜플형식

    def __str__(self):  # java로 따지면 toString()과 유사
        return self.name

    def __get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

from photo.fields import ThumbnailImageField    # 사용자 정의 커스텀 필드(우리가 직접 만듬)

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=50)
    description = models.TextField('Photo Description', blank=True)

    image = ThumbnailImageField('IMAGE', upload_to='photo/%Y/%m')   # 사용자 정의 커스텀 필드
    upload_dt = models.DateTimeField('UPLOAD DATE', auto_now_add=True)

    class Meta:
        ordering = ('title', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args = (self.id, ))

ch11/photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from photo.models import Album, Photo

# Create your views here.
class AlbumLV(ListView):    # 앨범 목록 보기
    model = Album

class AlbumDV(DetailView):  # 앨범 상세 보기
    model = Album

class PhotoDV(DetailView):  # 사진 상세 보기
    model = Photo

ch11/photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% block title %} 앨범 상세 보기 {% endblock %}

{% block extra-style %}
    <style>
        .thumbnail {border:5px solid #CCCCCC;}
    </style>
{% endblock %}

{% block content %}
    <div class="mt-5">
        <span class="h2">{{object.name}}&emsp;</span>
        <span class="h5 font-italic">{{object.description}}</span>

    </div>
    <hr style="margin : 0 0 20px 0;">
    <div class="row">
        {% for photo in object.photo_set.all %}
        <div class="col-md-3 mb-5">
            <div class="thumbnail">
                <a href="{{photo.get_absolute_url}}">
                    <img src="{{photo.image.thumb_url}}" style="width:100%;">
                </a>
            </div>
            <ul>
                <li class="font-italic">{{photo.title}}</li>
                <li class="font-italic">{{photo.upload_dt|date:"Y-m-d"}}</li>
            </ul>
        </div>
        {% endfor %}
    </div>
{% endblock %}

ch11/photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %} 앨범 목록 보기 {% endblock %}

{% block extra-style %}
    <style>
        .thumbnail {border:3px solid #CCC;}
    </style>
{% endblock %}

{% block content %}
    {% for item in object_list %}
        <div class="mt-5">
            <a class="h2" href="{% url 'photo:album_detail' item.id %}">{{item.name}}</a>
            <span class="font-italic h5">{{item.description}}</span>
        </div>

         <hr style="margin:0 0 20px 0;">

        <div class="row">
            {% for photo in item.photo_set.all|slice:":5"%}
                <div class="mt-5">
                    <div class="thumbnail">
                        <a href="{{photo.get_absoulte_url}}">
                            <img src="{{photo.image.thumb_url}}" style="width:100%;">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

ch11/photo/templates/photo/photo_detail.html
{% extends "base.html" %}
{% block title %}photo_detail.html{% endblock %}
{% block content %}
    <h2 class="mt-5">{{ object.title }}</h2>

    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%;">
            </a>
        </div>

        <ul class="col-md-3 mt-3">
            <li class = "h5">Photo Description</li>
                {% if object.description %}<p>{{object.description|linebreaks}}</p>
                {% else %}<p>(blank)</p>{% endif %}
            <li class="h5">Date Uploaded</li>
                <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">Album Name</li>
                <p class="font-italic">
                    <a href="{% url 'photo:album_detail' object.album.id %}">
{{ object.album.name }}</a>
                </p>
            </ul>
    </div>
{% endblock %}