ch12/blog/urls.py
from django.urls import path, re_path
from blog import views

# 이 파일은 ch03에서 신규 생성된다.
# blog를 위한 App Url파일이다.

app_name = 'blog'

urlpatterns = [
    # 호출 예시) /blog/
    path('', views.PostLV.as_view(), name='index'),

    # 호출 예시) /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 호출 예시) /blog/post/xxx/    정규식
    # r'정규표현식'의 r은 raw string의 줄인 말
    # cf) '\d'는 숫자 1개를 의미하고, r'\d'는 역슬래시 1개와 d를 찾아준다.
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDV.as_view(), name='post_detail'),

    # 호출 예시) /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # 호출 예시) /blog/archive/2021/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 호출 예시) /blog/archive/2021/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 호출 예시) /blog/archive/2021/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # 호출 예시) /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # 호출 예시) /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # 호출 예시) /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # 호출 예시) /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

ch12/bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

# 이 파일은 ch03에서 신규 생성되었다.
# blog를 위한 App Url 파일이다.

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),     # ch11에 수정됨

    # <int:pk>는 정수형 primary key를 의미할 것 같다고(-같다! 고 말하심)
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'), # ch11에 수정됨

    # ch11에 신규 추가됨
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),]

ch12/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include # ch03에서 추가됨
from mysite.views import HomeView # ch04에서 추가됨

from django.conf.urls.static import static # ch09에서 추가됨
from django.conf import settings    # ch09에서 추가됨

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 관리자를 위한 페이지
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'), # ch04에서 추가됨

    path('bookmark/', include('bookmark.urls')),    # ch03에서 추가됨
    path('blog/', include('blog.urls')),    # ch03에서 추가됨

    path('photo/', include('photo.urls')),  # ch09에서 추가됨

    # acoounts 항목들을 인증 기능(ch10)에서 추가됨
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='=register_done')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  # ch09에서 추가됨
    # Django의 보안상의 문제로 인해 새롭게 업로드 되는 이미지나 css, js파일과 같은 정적
    # 파일들의 경로를 실시간으로 읽어오지 못하기 때문에 뒤로 경로를 따로 설정해 주었다.


    # 기존 소스 주석 처리
    # # 사용자를 위한 페이지 - 사용자가 지정한 views
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    #
    # # <int:pk>는 정수형 primary key를 의미할 것 같다고(-같다! 고 말하심)
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),]

ch12/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns = [

    # 호출 예시: /photo/
    path('', views.AlbumLV.as_view(), name='index'),

    # 호출 예시: /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    # 호출 예시: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # 호출 예시: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # 호출 예시: /album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # 호출 예시: /album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # 호출 예시: /album/<int:pk>/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # 호출 예시: /album/<int:pk>/delete/
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),

    # 호출 예시: /photo/add/
    path('photo/add/', views.PhotoCreateView.as_view(), name='photo_add'),

    # 호출 예시: /photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # 호출 예시: /photo/<int:pk>/update/
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),

    # 호출 예시: /photo/<int:pk>/delete/
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
]

ch12/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">
    {# 다음은 메인 화면에 보여지는 상단의 네비게이션 바 영역입니다. #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a></li>
                <!-- 위의 href링크들을 통해서 네비게이션 바가 클릭됨-->

                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
                        <a class="dropdown-item"  href="{% url 'blog:add' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"  href="{% url 'photo:album_add' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
                        <a class="dropdown-item"  href="{% url 'blog:change' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"  href="{% url 'photo:album_change' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                    </div>
                </li>

                 <li class="nav-item dropdown mx-1 btn btn-primary">
                     <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                     <div class="dropdown-menu">
                         <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                         <div class="dropdown-divider"></div>
                         <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                         <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                     </div>
                 </li>
            </ul>

            <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
            </form>

            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    {% if user.is_active %}
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                        <div class="dropdown-menu">             <!--short_name : 성,  username : 이름 -->
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        </div>
                    {% endif %}
                </li>
            </ul>

        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% block footer %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/c998a172fe.js"></script>
</body>

ch12/templates/home.html
<html>
{% extends 'base.html' %}

{% load static %}

<head>
    {% block title %}home.html{% endblock title %}
    {% block extra-style %}
        <style type="text/css">
        .home-image {
            background-image: url("{% static 'img/lion.jpg' %}");
            background-repeat: no-repeat;
            background-position: center;
            background-size: 100%;
            height: 500px;
            border-top: 10px solid #ccc;
            border-bottom: 10px solid #ccc;
            padding: 20px 0 0 20px;
        }
        .title {
            color: #c80;
            font-weight: bold;
        }
        .powered {
            position: relative;
            top: 77%;
            color: #cc0;
            font-style: italic;
        }
        </style>
    {% endblock %}
</head>

<body>
{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="fixed-bottom bg-info">
        <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
    </footer>
{% endblock %}
{% block extra-script %}{% endblock %}
</body>

</html>