ch12/blog/urls.py
from django.urls import path, re_path
from blog import views

# 이 파일은 ch03에서 신규 생성된다.
# blog를 위한 App Url파일이다.

app_name = 'blog'

urlpatterns = [
    # 호출 예시) /blog/
    path('', views.PostLV.as_view(), name='index'),

    # 호출 예시) /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 호출 예시) /blog/post/xxx/    정규식
    # r'정규표현식'의 r은 raw string의 줄인 말
    # cf) '\d'는 숫자 1개를 의미하고, r'\d'는 역슬래시 1개와 d를 찾아준다.
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDV.as_view(), name='post_detail'),

    # 호출 예시) /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # 호출 예시) /blog/archive/2021/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 호출 예시) /blog/archive/2021/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 호출 예시) /blog/archive/2021/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # 호출 예시) /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # 호출 예시) /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # 호출 예시) /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    # 호출 예시) /blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

ch12/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include # ch03에서 추가됨
from mysite.views import HomeView # ch04에서 추가됨

from django.conf.urls.static import static # ch09에서 추가됨
from django.conf import settings    # ch09에서 추가됨

from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 관리자를 위한 페이지
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'), # ch04에서 추가됨

    path('bookmark/', include('bookmark.urls')),    # ch03에서 추가됨
    path('blog/', include('blog.urls')),    # ch03에서 추가됨

    path('photo/', include('photo.urls')),  # ch09에서 추가됨

    # acoounts 항목들을 인증 기능(ch10)에서 추가됨
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='=register_done')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  # ch09에서 추가됨
    # Django의 보안상의 문제로 인해 새롭게 업로드 되는 이미지나 css, js파일과 같은 정적
    # 파일들의 경로를 실시간으로 읽어오지 못하기 때문에 뒤로 경로를 따로 설정해 주었다.


    # 기존 소스 주석 처리
    # # 사용자를 위한 페이지 - 사용자가 지정한 views
    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    #
    # # <int:pk>는 정수형 primary key를 의미할 것 같다고(-같다! 고 말하심)
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'),]

ch12/blog/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager     # ch06에서 추가

# ch11에서 추가
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)  # 포스트 제목
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')  # 제목의 별칭
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')  # 포스트 한 줄 설명
    content = models.TextField('CONTENT')  # 포스트의 내용
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)  # 생성 일자
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)  # 수정 일자
    tags = TaggableManager(blank=True)  # ch06에서 추가됨
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)     # ch11에서 추가됨

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # blog 앱 중에서 url 이름이 post_detail인 항목을 찾아준다.
        # args는 매개 변수를 의미한다.
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    # 모델 객체를 데이터베이스에 저장해 준다.
    def save(self, *args, **kwargs):    # ch11에서 추가됨
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

ch12/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):   # django에 기본적으로 Form이 있음
    # html 형식 : <input type = "text" name = "Search_Word">
    search_word = forms.CharField(label="Search Word ")

ch12/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView \
    ,DayArchiveView, TodayArchiveView

from blog.models import Post

from django.views.generic import TemplateView

# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2     # 한 페이지에 두 개씩 보여줘라, pageSize

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    model_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    model_format = '%m'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    model_format = '%m'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        # 모델 매니저를 이용한 데이터 필터링
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 템플릿 문서에서 {{tagname}}라는 코드로 참조될 수 있다.
        context['tagname'] = self.kwargs['tag']
        return context

# pdf 143page
from django.views.generic import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

class SearchFormView(FormView):

    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):     # 유효성 검사를 통과한 다음 호출이 되는 메소드, callback 함수

        # cleaned_data 메소드는 유효성 검사를 통과한 다음 해당 필드들의 정보를 보여준다.
        searchWord = form.cleaned_data['search_word']
        # JSP형식 : String searchWord = request.getParameter("Search_Word");
        
        # objects는 모델 매니저 이름
        post_list = Post.objects.filter(Q(title__icontains=searchWord) |
Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()
        context = {}    # 템플릿에서 참조될 컨택스트 정보
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context) # No Redirection

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

# reverse_lazy() 함수는 reverse() 함수와 동일한 개념이지만
# urls.py 파일이 먼저 실행되고, 이후에 조금 늦게 view.py파일이 동작하도록 하는 함수이다.
from django.urls import reverse_lazy

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    # initial 속성은 폼 양식에 들어갈 기본 값을 지정한다.
    initial = {'slug':'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

from mysite.views import OwnerOnlyMixin
from django.views.generic import UpdateView
from django.views.generic import DeleteView

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

ch12/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}
    <h2>Blog List</h2>

    {% for post in posts %}
        <h3>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
        </h3>
        {{post.modify_dt | date:"N d, Y"}}
        <p>{{post.description}}</p>
    {% endfor %}
    <br>
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">PreviousPage</a>
            {% endif %}
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">NextPage</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

ch12/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}post_archive.html{% endblock %}

{% block content %}
<h1>Post Archive until {% now "N d, Y" %}</h1>
    <ul>
        {% for date in date_list %}
            <li style="display:inline;">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year--{{date|date:"Y"}}</a>
            </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li> {{post.modify_dt|date:"Y-m-d"}}&nbsp;&nbsp;&nbsp;
                <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

ch12/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

ch12/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}post_archive_month.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ month|date:"N Y" }}</h1>
<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}
                &nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

ch12/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1>
<ul>
    {% for date in date_list %}
    <li style="display: inline;">
        <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a>
    </li>
    {% endfor %}
</ul>
<br>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

ch12/blog/templates/blog/post_change_list.html
{% extends "base.html" %}
{% block title %}post_change_list.html{% endblock %}
{% block content %}
    <h1>Post Change - {{user}}</h1>
    <br>

    <table class="table table-bordered table-sm table-striped">
        <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
                <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

ch12/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}post_confirm_delete.html{% endblock %}
{% block content %}
    <h1>Post Delete</h1>
    <br>
    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}

ch12/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}post_archive_year.html{% endblock %}

{% block content %}
<h2>제목 : {{object.title}}</h2>
<p>
    {% if object.get_previous %}
        <a href="{{object.get_previous.get_absolute_url}}">
            &laquo;--   {{object.get_previous}}
        </a>
    {% endif %}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    {% if object.get_next %}
        <a href="{{object.get_next.get_absolute_url}}">
            {{object.get_next}} --&raquo;
        </a>
    {% endif %}
</p>
    <p>{{object.modify_dt|date:"j F Y"}}</p>
<br>
<div>{{object.content|linebreaks}}</div>

<br>
<div>
    <b>Tags</b><i class="'fas fa-tag"></i>
    {# 커스텀 태그를 사용하기 위하여 해당 모듈을 로딩한다. #}
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as "tags" %}
    {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">
            {{tag.name}}
        </a>
    {% endfor %}
</div>

{% endblock %}

ch12/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
    post_form.html
{% endblock %}
{% block content %}
    <h1>Post 생성/수정 - {{user}}</h1>
    <p class="font-italic">블로그를 위한 생성/수정 화면이다.</p>
    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">
                다음 문제에 대하여 수정을 해주셔야 한다.
            </div>
            {{form.errors}}
        </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{form.title|add_label_class:"col-from-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-5">
                {{form.title|add_class:"form-control"|attr:"autofocus"}}
            </div>
        </div>
        <div class="form-group row">
            {{form.slug|add_label_class:"col-from-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-5">
                {{form.slug|add_class:"form-control"|attr:"readonly"}}
            </div>
            <small class="form-text text-myted">{{form.slug.help_text}}</small>
        </div>
        <div class="form-group row">
            {{form.description|add_label_class:"col-from-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-5">
                {{form.description|add_class:"form-control"}}
            </div>
            <small class="form-text text-myted">{{form.description.help_text}}</small>
        </div>
        <div class="form-group row">
            {{form.content|add_label_class:"col-from-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-5">
                {{form.content|add_class:"form-control"|attr:"autofocus"}}
            </div>
        </div>
        <div class="form-group row">
            {{form.tags|add_label_class:"col-from-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-5">
                {{form.tags|add_class:"form-control"|attr:"autofocus"}}
            </div>
        </div>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-3">
                <input type="submit" value="Submit" class="btn btn-info">
            </div>
        </div>
    </form>
{% endblock %}

ch12/blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title %}post_search.html{% endblock %}
{% block content %}
    <h1>Blog Search</h1><br>
    <form action="." method="post">{% csrf_token %}
        {{form.as_table}}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form><br/><br/>

    {% if object_list %}
        {% for post in object_list %}
            <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
            {{post.modify_dt | date:"N d, Y"}}
            <p>{{post.description}}</p>
        {% endfor %}
    {% elif search_term %}
        <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}
{% endblock %}